MODEL:
  META_ARCHITECTURE: "DeepForest"
  BACKBONE:
    NAME: "DeepForestBackbone"
  DEEPFOREST_PRETRAINED: "birddetector"
  RETINANET:
    NMS_THRESH_TEST: 0.2
    SCORE_THRESH_TEST: 0.2
SOLVER:
  BASE_LR: 0.001
VERSION: 2