MODEL:
  META_ARCHITECTURE: "DeepForest"
  BACKBONE:
    NAME: "DeepForestBackbone"
  DEEPFOREST_PRETRAINED: "deepforest"
  RETINANET:
    NMS_THRESH_TEST: 0.05
    SCORE_THRESH_TEST: 0.1
SOLVER:
  BASE_LR: 0.001
VERSION: 2