MODEL:
  META_ARCHITECTURE: "YOLOv5"
  NUM_CLASSES: 80
  YOLO:   # config properties of YOLOv5 model; see https://github.com/ultralytics/yolov5/tree/master/models
    depth_multiple: 0.33  # model depth multiple
    width_multiple: 0.50  # layer channel multiple
    anchors:
    - [10,13, 16,30, 33,23]  # P3/8
    - [30,61, 62,45, 59,119]  # P4/16
    - [116,90, 156,198, 373,326]  # P5/32

    # YOLOv5 v6.0 backbone
    backbone:
      # [from, number, module, args]
      [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
      [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
      [-1, 3, C3, [128]],
      [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
      [-1, 6, C3, [256]],
      [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
      [-1, 9, C3, [512]],
      [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
      [-1, 3, C3, [1024]],
      [-1, 1, SPPF, [1024, 5]],  # 9
      ]

    # YOLOv5 v6.0 head
    head:
      [[-1, 1, Conv, [512, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 6], 1, Concat, [1]],  # cat backbone P4
      [-1, 3, C3, [512, False]],  # 13

      [-1, 1, Conv, [256, 1, 1]],
      [-1, 1, nn.Upsample, [None, 2, 'nearest']],
      [[-1, 4], 1, Concat, [1]],  # cat backbone P3
      [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

      [-1, 1, Conv, [256, 3, 2]],
      [[-1, 14], 1, Concat, [1]],  # cat head P4
      [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

      [-1, 1, Conv, [512, 3, 2]],
      [[-1, 10], 1, Concat, [1]],  # cat head P5
      [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

      [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
      ]
    
    HYP:    # default hyperparameters; taken from https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch-low.yaml. Currently only contains parameters actually used in AIDE trainer; expand in future
      cls_pw: 1.0  # cls BCELoss positive_weight
      obj_pw: 1.0  # obj BCELoss positive_weight
      label_smoothing: 0.0
      fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
      box: 0.05  # box loss gain
      obj: 1.0  # obj loss gain (scale with pixels)
      cls: 0.5  # cls loss gain
      anchor_t: 4.0  # anchor-multiple threshold
      nms_conf_thres: 0.25
      nms_iou_thres: 0.45
      nms_single_cls: false
      nms_max_det: 300
DATASETS:   # just here to get initial 80 label classes (TODO: check on YOLOv5 side)
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
LABELCLASS_NAMES:
  - "person"
  - "bicycle"
  - "car"
  - "motorcycle"
  - "airplane"
  - "bus"
  - "train"
  - "truck"
  - "boat"
  - "traffic light"
  - "fire hydrant"
  - "stop sign"
  - "parking meter"
  - "bench"
  - "bird"
  - "cat"
  - "dog"
  - "horse"
  - "sheep"
  - "cow"
  - "elephant"
  - "bear"
  - "zebra"
  - "giraffe"
  - "backpack"
  - "umbrella"
  - "handbag"
  - "tie"
  - "suitcase"
  - "frisbee"
  - "skis"
  - "snowboard"
  - "sports ball"
  - "kite"
  - "baseball bat"
  - "baseball glove"
  - "skateboard"
  - "surfboard"
  - "tennis racket"
  - "bottle"
  - "wine glass"
  - "cup"
  - "fork"
  - "knife"
  - "spoon"
  - "bowl"
  - "banana"
  - "apple"
  - "sandwich"
  - "orange"
  - "broccoli"
  - "carrot"
  - "hot dog"
  - "pizza"
  - "donut"
  - "cake"
  - "chair"
  - "couch"
  - "potted plant"
  - "bed"
  - "dining table"
  - "toilet"
  - "tv"
  - "laptop"
  - "mouse"
  - "remote"
  - "keyboard"
  - "cell phone"
  - "microwave"
  - "oven"
  - "toaster"
  - "sink"
  - "refrigerator"
  - "book"
  - "clock"
  - "vase"
  - "scissors"
  - "teddy bear"
  - "hair drier"
  - "toothbrush"
VERSION: 2