# Docker compose GitHub action configuration.
#
# 2024 Benjamin Kellenberger

name: Docker build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: hoverkraft-tech/compose-action@v2.0.0
      with:
        compose-file: docker-compose.yml
        cwd: "./docker"