# GitHub actions workflow configuration for Ubuntu build.
#
# 2024 Benjamin Kellenberger

name: Ubuntu build

on: [push, pull_request]

jobs:
  python_packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        pytorch: [
          {torch: "2.0.1", torchvision: "0.15.2"},
          {torch: "2.1.2", torchvision: "0.16.2"},
          {torch: "2.2.2", torchvision: "0.17.2"},
          {torch: "2.3.0", torchvision: "0.18.0"},
        ]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential wget libpq-dev python3 ffmpeg libsm6 libxext6 libglib2.0-0 python3-opencv python3-pip gdal-bin libgdal-dev
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          activate-environment: aide
          python-version: ${{ matrix.python-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install torch==${{matrix.pytorch.torch}} torchvision==${{matrix.pytorch.torchvision}} --index-url https://download.pytorch.org/whl/cpu
          python -m pip install git+https://github.com/facebookresearch/detectron2.git
          python -m pip install -U -r requirements.txt
      - name: Verify dependencies
        run: python install/verify_installed_libs.py --raise-on-error=1
      # - name: Run unit tests
      #   run: |
      #     python3 -m pip install pytest pytest-cov
      #     python3 -m pytest tests.py
      