# Main GitHub actions workflow configuration.
#
# 2024 Benjamin Kellenberger

name: AIDE

on: [push]

jobs:
  python_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.8", "pypy3.9", "3.8", "3.9", "3.10"]
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install torch torchvision
          python -m pip install -U requirements.txt
      
      - name: Run unit tests
        run: |
          python -m pip install pytest pytest-cov
          python -m pytest tests.py
      